spring.config.import=optional:secrets.properties
spring.application.name=userservices
server.port=8083
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost
# Connection URI for MongoDB (including username, password, and the database)
spring.data.mongodb.uri=mongodb+srv://arunabegum700_db_user:BTAyPZWMuPV4qavB@cluster0.yjuxfea.mongodb.net

# Optionally, you can still specify the database
spring.data.mongodb.database=mydb

